###
# User Manager
###

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    cluster: management
    component: user-manager
  name: user-manager
  namespace: __NPH_NAMESPACE
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      cluster: management
      component: user-manager
  template:
    metadata:
      labels:
        cluster: management
        component: user-manager
    spec:
      containers:
      - name: user-manager
        image: __NPH_REGISTRY.azurecr.io/__NPH_REGISTRY_NAMESPACE/user-manager:__NPH_VERSION
        imagePullPolicy: Always
        args:
        - "run"
        - "--debug"
        - "--systemModelAddress=system-model.__NPH_NAMESPACE:8800"
        - "--authxAddress=authx.__NPH_NAMESPACE:8810"
        securityContext:
          runAsUser: 2000
      imagePullSecrets:
      - name: nalej-registry
